#!/bin/bash
# Generated by ChatGPT

DOMAIN="local.banfan.app"
HOSTS_LINE="127.0.0.1 $DOMAIN"

echo "🔧 準備開始設定 HTTPS 開發環境 for $DOMAIN"

# 1. 檢查是否已安裝 mkcert
if ! command -v mkcert &> /dev/null; then
  echo "📦 mkcert 未安裝，正在使用 Homebrew 安裝..."
  brew install mkcert
else
  echo "✅ mkcert 已安裝"
fi

# 2. 安裝本機根憑證
echo "📥 安裝本機憑證（需要密碼）..."
mkcert -install

# 3. 產生憑證
echo "🔐 為 $DOMAIN 產生 SSL 憑證..."
mkcert "$DOMAIN"

# 4. 修改 hosts 檔案
echo "📄 檢查 /etc/hosts 是否已包含 $DOMAIN..."

if grep -q "$DOMAIN" /etc/hosts; then
  echo "✅ $DOMAIN 已存在於 /etc/hosts"
else
  echo "🔧 新增 $DOMAIN 到 /etc/hosts（需要密碼）..."
  echo "$HOSTS_LINE" | sudo tee -a /etc/hosts > /dev/null
  echo "✅ 已加入 $DOMAIN 到 hosts"
fi

# 5. 完成提示
echo "👉 請用 https://$DOMAIN 測試你的本地伺服器"
